version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-stakepad
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - '${DB_PORT}:${DB_PORT}'
